### ISSUE TITLE
constraints to center? iPad display is topLeft..

### ISSUE THREAD

**Issue by wdcurry** [BalestraPatrick/WhatsNew#27]
hey, wondering if anyone already has tweaks setup to constrain display to show properly on an iPad.

**Comment by BalestraPatrick** [comment]
Hey @wdcurry, can you describe your problem in more details please?

**Comment by wdcurry** [comment]
Sure..i have standard (and well done, thanks!) WhatsNew setup for my iPhone devices. My app is essentially iPhone only but experience has taught me to drop up iPad images as well to get past reviewers. The WhatsNew displays, using the built-in viewcontroller, with no constraints and no adjustments to sizing. I can live without the dynamic font size constraints but having the off-center and iPhone sized display in the upper left is challenging to submit. I may leave as-is and just see how it goes.. unless of course i have missed a simple .setForIPad flag etc ;)

**Comment by BalestraPatrick** [comment]
Hey @wdcurry. If you project is Universal, the `WhatsNewViewController` will display something like as follows:
<img width="697" alt="screen shot 2018-08-12 at 2 15 03 pm" src="https://user-images.githubusercontent.com/3658887/44001894-6785e790-9e3a-11e8-97eb-537088a317ec.png">

You are always free to set bigger font dimensions to fit the bigger screen, but I think support for iPad is already built in since the layout looks good on all devices.

**Comment by jdanthinne** [comment]
On iPad, I use `whatsNew.modalPresentationStyle = .formSheet`.
